name: WorkFlow Hero

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello workflow
        run: echo "Watch git in action"
        shell: bash
  goodbye:
    runs-on: ubuntu-lates
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash
